name: SimplePlugin
version: 1.4.0
api: [3.0.0, 3.9.3, 4.0.0]
main: TestPlugin\Main
author: Alyx903, esh123unicorn
commands:
  test:
     default: op
     permission: test.use
     description: says hello
